version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker info
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -f ut.Dockerfile -t softwaregroup/ut-docker:latest -t softwaregroup/ut-docker:8.0.9 .
     - run: docker build -f impl.Dockerfile -t softwaregroup/impl-docker:latest -t softwaregroup/impl-docker:8.0.9 .
     - run: docker push softwaregroup/ut-docker:latest
     - run: docker push softwaregroup/ut-docker:8.0.9
     - run: docker push softwaregroup/impl-docker:latest
     - run: docker push softwaregroup/impl-docker:8.0.9