version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker info
     - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -t softwaregroup/ut-docker:latest -t softwaregroup/ut-docker:7.0.10 .
     - run: docker push softwaregroup/ut-docker:latest
     - run: docker push softwaregroup/ut-docker:7.0.10