version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker info
     - run:
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
         docker build --rm=false -t softwaregroup/ut-docker .
     - run: docker push softwaregroup/ut-docker