machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t softwaregroup/ut-docker .

test:
  override:
    - docker run -it softwaregroup/ut-docker npm ls ut-run

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push softwaregroup/ut-docker
